// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyhVEzPM_txzYfvIW2pS8awJy02yiZWV4',
    appId: '1:671551298394:android:e2ff26e9c66b44ff647163',
    messagingSenderId: '671551298394',
    projectId: 'eco-bin-b4be5',
    storageBucket: 'eco-bin-b4be5.firebasestorage.app',
    databaseURL:
        'https://eco-bin-b4be5-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOvUoN2axmFWIaWPc4I_BGx6JmklMdA9Q',
    appId: '1:671551298394:ios:51ea0aef133aff8d647163',
    messagingSenderId: '671551298394',
    projectId: 'eco-bin-b4be5',
    storageBucket: 'eco-bin-b4be5.firebasestorage.app',
    iosBundleId: 'com.example.mastersFinalApp',
    databaseURL:
        'https://eco-bin-b4be5-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOvUoN2axmFWIaWPc4I_BGx6JmklMdA9Q',
    appId: '1:671551298394:ios:139720c908236ad6647163',
    messagingSenderId: '671551298394',
    projectId: 'eco-bin-b4be5',
    storageBucket: 'eco-bin-b4be5.firebasestorage.app',
    iosBundleId: 'com.example.app',
    databaseURL:
        'https://eco-bin-b4be5-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDam-X0WLHuVN7xllk08t-Rq5n72zpLL3I',
    appId: '1:671551298394:web:b1300c45c1ae2403647163',
    messagingSenderId: '671551298394',
    projectId: 'eco-bin-b4be5',
    authDomain: 'eco-bin-b4be5.firebaseapp.com',
    storageBucket: 'eco-bin-b4be5.firebasestorage.app',
    measurementId: 'G-0WCVELG3WC',
    databaseURL:
        'https://eco-bin-b4be5-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDam-X0WLHuVN7xllk08t-Rq5n72zpLL3I',
    appId: '1:671551298394:web:3c14e2575fc269cb647163',
    messagingSenderId: '671551298394',
    projectId: 'eco-bin-b4be5',
    authDomain: 'eco-bin-b4be5.firebaseapp.com',
    storageBucket: 'eco-bin-b4be5.firebasestorage.app',
    measurementId: 'G-QX8JH1LX34',
    databaseURL:
        'https://eco-bin-b4be5-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
